### ISSUE TITLE
Add a "show materials for a single frame" function

### ISSUE THREAD

**Issue by crubleigh** [rebane2001/mapartcraft#103] opened 2020-09-07 07:10 UTC
Or something to that effect, even better would be if it showed the maximum amount of each material used for any single frame. This way, players that are using recycled plots and re-using materials will know how much materials to gather. Suppose I have a multi-frame map that wants me to use 10 shulkers of emerald blocks for the whole thing. If I recycle frames, then I would only need to collect as many emerald blocks as appear in the frame that has the most emerald blocks. Essentially you could show the minimum number of blocks required to build the map assuming each frame is recycled. As it stands right now the only way to figure this out would be to load each schematic into the world and check the materials list for each frame, which is kind of a pain in the ass. This feature would really only be applicable to 1.14+ players since recycling maps without locking them is kinda sus but help us out here.

**Comment by rebane2001** [comment] 2020-10-01 17:20
Dupe of #59

**Closed by rebane2001** 2020-10-01 17:20 UTC
